# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_ver: 1.0.0
    steps:
    - uses: actions/checkout@v4
    - run: mkdir build
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore '/p:SptRoot=build'
    # - name: Compress result
    #  run: zip -r ../ORBIT-{{ env.build_ver }}-rc.zip ./build/*
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Application_Artifact
        path: build/
